# Generated by Django 4.2.1 on 2023-05-16 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_banner_image_alter_lesson_mosque'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата урока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время конца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Мужчины'), ('FEMALE', 'Женщины')], default=django.utils.timezone.now, max_length=300, verbose_name='Для кого'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала'),
            preserve_default=False,
        ),
    ]
