# Generated by Django 4.2.1 on 2023-05-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_date_lesson_end_time_lesson_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(verbose_name='Дата урока'),
        ),
    ]
