# Generated by Django 4.2.1 on 2023-05-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='periodicity',
            field=models.BooleanField(default=False, verbose_name='Периодичность'),
        ),
    ]
