# Generated by Django 4.2.1 on 2023-05-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Мужчины'), ('FEMALE', 'Женщины')], max_length=7, verbose_name='Для кого'),
        ),
    ]
