# Generated by Django 4.2.1 on 2023-05-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_lesson_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='periodicity',
            field=models.BooleanField(default=False, verbose_name='Еженедельно'),
        ),
    ]
