# Generated by Django 4.2.1 on 2023-05-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_lesson_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной'),
        ),
    ]
