# Generated by Django 4.2.1 on 2023-07-31 05:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_banner_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Уровень урока',
                'verbose_name_plural': 'Уровни уроков',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Старт курса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(verbose_name='День недели'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='degree_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.lessondegree', verbose_name='Уровень урока'),
        ),
    ]
