# Generated by Django 4.2.1 on 2023-08-25 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_lesson_week_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
    ]
