# Generated by Django 4.2.1 on 2023-08-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_remove_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='week_day',
            field=models.CharField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], max_length=7, verbose_name='День недели'),
        ),
    ]
